# Generated by Django 4.1.5 on 2023-02-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=200)),
                ('p1', models.CharField(max_length=200)),
                ('p2', models.CharField(max_length=200)),
                ('p3', models.CharField(max_length=200)),
                ('p4', models.CharField(max_length=200)),
                ('p5', models.CharField(max_length=200)),
                ('p6', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeamCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerCount', models.IntegerField()),
            ],
        ),
    ]
