# Generated by Django 4.1.5 on 2023-02-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRosters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1_name', models.CharField(max_length=200)),
                ('p1_team1', models.CharField(max_length=200)),
                ('p2_team1', models.CharField(max_length=200)),
                ('p3_team1', models.CharField(max_length=200)),
                ('p4_team1', models.CharField(max_length=200)),
                ('p5_team1', models.CharField(max_length=200)),
                ('p6_team1', models.CharField(max_length=200)),
                ('team_2_name', models.CharField(max_length=200)),
                ('p1_team2', models.CharField(max_length=200)),
                ('p2_team2', models.CharField(max_length=200)),
                ('p3_team2', models.CharField(max_length=200)),
                ('p4_team2', models.CharField(max_length=200)),
                ('p5_team2', models.CharField(max_length=200)),
                ('p6_team2', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamCount',
        ),
    ]
