# Generated by Django 4.1.5 on 2023-02-09 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_creator', '0003_players'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Players',
        ),
    ]
