# Generated by Django 4.1.5 on 2023-02-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_creator', '0005_gamerosters_p11_makes_gamerosters_p11_misses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerosters',
            name='team1_cups',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='gamerosters',
            name='team2_cups',
            field=models.IntegerField(default=100),
        ),
    ]
